package good

type AutoGenerated struct {
	ID    int64 `json:"id,omitempty"`
	Store Store `json:"store,omitempty"`
}

type Specs struct {
	SpecKey     string `json:"spec_key,omitempty"`
	SpecValue   string `json:"spec_value,omitempty"`
	SpecKeyID   int64  `json:"spec_key_id,omitempty"`
	SpecValueID int64  `json:"spec_value_id,omitempty"`
}

type Skus struct {
	GoodsID      uint64  `json:"goodsID,omitempty"`
	SkuID        int64   `json:"skuId,omitempty"`
	SkuID0       int64   `json:"skuID,omitempty"`
	ThumbURL     string  `json:"thumbUrl,omitempty"`
	InitQuantity int     `json:"initQuantity"`
	Quantity     int     `json:"quantity,omitempty"`
	Specs        []Specs `json:"specs,omitempty"`
	Spec         string  `json:"spec,omitempty"`
	NormalPrice  float64 `json:"normalPrice,omitempty"`
	GroupPrice   float64 `json:"groupPrice,omitempty"`
	SkuPrice     int     `json:"skuPrice,omitempty"`
}

type DetailGallery struct {
	URL    string `json:"url,omitempty"`
	Width  int    `json:"width,omitempty"`
	Height int    `json:"height,omitempty"`
}

type TopGallery struct {
	URL string `json:"url,omitempty"`
}

type GoodsProperty struct {
	Key    string   `json:"key,omitempty"`
	Values []string `json:"values,omitempty"`
	RefPid int64    `json:"ref_pid,omitempty"`
}

type Goods struct {
	GoodsID       uint64          `json:"goodsID,omitempty"`
	GoodsType     int             `json:"goodsType,omitempty"`
	GoodsName     string          `json:"goodsName,omitempty"`
	Code          string          `json:"code,omitempty"`
	ShareDesc     string          `json:"shareDesc,omitempty"`
	CatID         int             `json:"catID,omitempty"`
	CatID1        uint32          `json:"catID1,omitempty"`
	CatID2        uint32          `json:"catID2,omitempty"`
	CatID3        uint32          `json:"catID3,omitempty"`
	CatID4        uint32          `json:"catID4"`
	Skus          []Skus          `json:"skus,omitempty"`
	DetailGallery []DetailGallery `json:"detailGallery,omitempty"`
	TopGallery    []TopGallery    `json:"topGallery,omitempty"`
	ThumbURL      string          `json:"thumbUrl,omitempty"`
	HdThumbURL    string          `json:"hdThumbUrl,omitempty"`
	GoodsProperty []GoodsProperty `json:"goodsProperty,omitempty"`
	LinePrice     string          `json:"linePrice,omitempty"`
}

type InitDataObj struct {
	Goods Goods `json:"goods,omitempty"`
}

type Store struct {
	InitDataObj InitDataObj `json:"initDataObj,omitempty"`
}
