package site_monitor

type Item struct {
	RedirectCount         float64 `json:"redirectCount"`
	DiagnosisMtrID        string  `json:"diagnosisMtrId"`
	SSLConnectTime        float64 `json:"SSLConnectTime"`
	AssertionResults      string  `json:"assertionResults"`
	PingDetail            string  `json:"pingDetail"`
	HTTPConnectTime       float64 `json:"HTTPConnectTime"`
	Isp                   string  `json:"isp"`
	ErrorCode             float64 `json:"errorCode"`
	TargetProvinceCN      string  `json:"targetProvinceCN"`
	IspCN                 string  `json:"ispCN"`
	Resolution            string  `json:"resolution"`
	PingSentNum           string  `json:"pingSentNum"`
	AreaEN                string  `json:"areaEN"`
	TaskEndTimestamp      int64   `json:"taskEndTimestamp"`
	DiagnosisPingID       string  `json:"diagnosisPingId"`
	TargetIspEN           string  `json:"targetIspEN"`
	TotalTime             float64 `json:"TotalTime"`
	DNSServer             string  `json:"dnsServer"`
	TaskStartTimestamp    int64   `json:"taskStartTimestamp"`
	CountryCN             string  `json:"countryCN"`
	ProvinceEN            string  `json:"provinceEN"`
	CountryEN             string  `json:"countryEN"`
	PingDetailFormatted   string  `json:"pingDetailFormatted"`
	Head                  string  `json:"Head"`
	DNSRaw                string  `json:"DNSRaw"`
	TargetCityEN          string  `json:"targetCityEN"`
	CurlConnectTime       float64 `json:"curlConnectTime"`
	RouteJSON             string  `json:"routeJson"`
	Mxs                   string  `json:"mxs"`
	TargetCountryCN       string  `json:"targetCountryCN"`
	Ips                   string  `json:"ips"`
	CurlPretransferTime   float64 `json:"curlPretransferTime"`
	TargetIP              string  `json:"targetIp"`
	Route                 string  `json:"route"`
	SourceIP              string  `json:"sourceIp"`
	Txts                  string  `json:"txts"`
	TCPConnectTime        float64 `json:"tcpConnectTime"`
	CityEN                string  `json:"cityEN"`
	PingMinTime           string  `json:"pingMinTime"`
	HTTPDownloadTime      float64 `json:"HTTPDownloadTime"`
	HTTPResponseCode      float64 `json:"HTTPResponseCode"`
	ResponseBody          string  `json:"responseBody"`
	AreaCN                string  `json:"areaCN"`
	City                  string  `json:"city"`
	Expection             string  `json:"expection"`
	PingMaxTime           string  `json:"pingMaxTime"`
	TargetProvinceEN      string  `json:"targetProvinceEN"`
	Nss                   string  `json:"nss"`
	SuorceIP              string  `json:"suorceIp"`
	IspEN                 string  `json:"ispEN"`
	HTTPDNSTime           float64 `json:"HTTPDNSTime"`
	TargetIsp             string  `json:"targetIsp"`
	CurlStarttransferTime float64 `json:"curlStarttransferTime"`
	ProvinceCN            string  `json:"provinceCN"`
	PingReceivedNum       string  `json:"pingReceivedNum"`
	Timestamp             int64   `json:"timestamp"`
	RedirectTime          float64 `json:"redirectTime"`
	TargetCity            string  `json:"targetCity"`
	Message               string  `json:"message"`
	UserID                string  `json:"userId"`
	Cnames                string  `json:"cnames"`
	FailureRate           string  `json:"failureRate"`
	Expect                string  `json:"expect"`
	HTTPDownloadSize      float64 `json:"HTTPDownloadSize"`
	TargetCountryEN       string  `json:"targetCountryEN"`
	LocalDNS              string  `json:"localDns"`
	RequestHeader         string  `json:"RequestHeader"`
	CityCN                string  `json:"cityCN"`
	TaskID                string  `json:"taskId"`
}
